const data_synonyms = {
     "WarCraft":"WC|WCIII|WarIII|Frozen Throne|W3",
     "StarCraft": "BW|Brood War|Broodwar|SC|SCII|Heart of the Swarm|Legacy of the Void|Wings of Liberty",
     "Dawn of War":"DOW|Warhammer 40,000|w40k|warhammer 40k",
     "Supreme Commander": "SupCom|Forged Alliance",
     "Halo Wars":"HW|Halowars",
     "Age of Mythology":"AoM",
     "Ashes of the Singularity":"AotS",
     "Command & Conquer": "C&C|CnC|RA|Red Alert|Command and Conquer|Tiberium Wars",
     "Company of Heroes": "CoH",
     "Battle for Middle Earth": "BFME|Battle for Middle-Earth|LOTR|Lord of the Rings",
     "Age of Empires":"AoE",
     "Universe at War":"UAW",
     "Total Annihilation": "TA",
     "League of Legends": "lol",
     'Heroes from the Storm':'hots',
     'Magic: The Gathering':'mtg',
     'Dungeons & Dragons':  'Dungeons and Dragons',
     'Total War': 'totalwar'
     };

const data_rts = [
      '0 A.D',
      '7th Legion',
      '4x',
      '8-Bit',
      'A Year of Rain',
      'ARSENAL',
      'Achron',
      'Act of Aggression',
      'Act of War',
      'Against Rome',
      'Age of Empires',
      'Age of Mythology',
      'Aggression: Reign Over Europe',
      'AirMech',
      'Alexander',
      'Alien Legacy',
      'Alien Nations',
      'Allegiance',
      'America',
      'American Conquest',
      'Ancestors Legacy',
      'Ancient Art of War in the Skies, The',
      'Ancient Space',
      'Ancient Wars: Sparta',
      'Anno',
      'Arena Wars',
      'Armies of Exigo',
      'Army Men: RTS',
      'Ashes of the Singularity',
      'Atrox',
      'Axis and Allies',
      'BANNERMEN',
      'Baldies',
      'Battle Command',
      'Battle Isle: The Andosia War',
      'Battle Realms',
      'BattleForge',
      'Battlefleet Gothic: Armada',
      'Battles of the Outer Rim',
      'Battlezone',
      'Beasts and Bumpkins',
      'Black Moon Chronicles',
      'Blitzkrieg 3',
      'Blood & Magic',
      'Bokosuka Wars',
      'Bos Wars',
      'Brutal Legend',
      'Cannon Fodder',
      'Carrier Command',
      'Castle Strike',
      'Celtic Kings: Rage of War',
      'Clash Royale',
      'Colobot',
      'Combat Leader',
      'Command & Conquer',
      'Command HQ',
      'Command: Chains of War',
      'Command: Modern Air Naval Operations',
      'Company of Heroes',
      'Conflict Zone',
      'Confrontation: Peace Enforcement',
      'Conquest Earth',
      'Conquest: Frontier Wars',
      'Cosmic Conquest',
      'Cossacks',
      'Conan',
      'Creeper World',
      'Crusader Kings',
      'Cultures 2: The Gates of Asgard',
      'Cultures: Discovery of Vinland',
      'Cytron Masters',
      'D-Day',
      'DEFCON: Everybody Dies',
      'Dark Colony',
      'Dark Planet: Battle for Natrolis',
      'Dark Reign',
      'Darwinia',
      'Diablo',
      'Dawn of Fantasy',
      'Desert Rats vs Afrika Korps',
      "Dota",
      'Dogs of War: Battle On Primus IV',
      'Dominant Species',
      'Dominion: Storm Over Gift 3',
      'Dragon Force',
      'Dragon Throne: Battle of Red Cliffs',
      'Dune 2000',
      'Dune II',
      'Dwarfheim',
      'Dungeons & Dragons',
      'Earth 2140',
      'Earth 2150',
      'Earth 2160',
      'Emperor: Battle for Dune',
      'Empire Earth',
      'Empires Apart',
      'Empire at War',
      'Empires: Dawn of the Modern World',
      'Enemy Nations',
      'Energy Warrior',
      'Etherium',
      'Europa Universalis',
      "EvE Online",
      'Evil Genius',
      'Evolution RTS',
      'Executive Assault',
      'Eximius: Seize the Frontline',
      'Exodus: The Last War',
      'Extreme Tactics',
      'Faces of War',
      'Fate of Hellas',
      'Final Conflict',
      'Forged Battalion',
      'Foundation',
      'Fragile Allegiance',
      'Gain Ground',
      'Gangland',
      'Genesis Rising: The Universal Crusade',
      'Genewars',
      'Genius: Biology',
      'Giants: Citizen Kabuto',
      'Glest',
      'Globulation 2',
      'Great Invasions',
      'Grey Goo',
      'GrimGrimoire',
      'Ground Control',
      'Guardians of Atlas',
      'HYPERNOVA: Escape from Hadea',
      'Haegemonia: Legions of Iron',
      'Halo Wars',
      'Hanjuku Eiyuu - Aa Sekai Yo Hanjuku Nare',
      'Hearts of Iron',
      'Heroes from the Storm',
      'Hegemony Gold: Wars of Ancient Greece',
      'Hegemony III: Clash of the Ancients',
      'Hegemony Rome: The Rise of Caesar',
      'Heroes of Annihilated Empires',
      'Heroes of Mana',
      'Herzog',
      'Highland Warriors',
      'Homeworld',
      'Hostile Waters: Antaeus Rising',
      'Hundred Swords',
      'I of the Dragon',
      'Illyriad',
      'Imperator: Rome',
      'Imperium Galactica',
      'Imperivm: Great Battles of Rome',
      'Impossible Creatures',
      'Inkawar',
      'Invasion',
      'Iron Harvest',
      'Iron Seed',
      "J.R.R. Tolkien's Riders of Rohan",
      "J.R.R. Tolkien's War in Middle-earth",
      "Jeff Wayne's The War of the Worlds",
      'Judgment: Apocalypse Survival Simulation',
      'Jurassic War',
      'K240',
      'KKND',
      'Kingdom Under Fire: A War of Heroes',
      'Kingdom Wars 2: Battles',
      'KnightShift',
      'Knights and Merchants:',
      'Knights of Honor',
      'Kohan',
      'Konung 2: Blood of Titans',
      "League of Legends",
      'L.E.D. Wars, The',
      'LEGO Rock Raiders',
      'Legionnaire',
      'Battle for Middle Earth',
      'Lords of Everquest',
      'Loria',
      'LostMagic',
      'MAD: Global Thermonuclear War',
      'Machines',
      'Magic: The Gathering',
      'Maelstrom',
      'Magic and Mayhem',
      'Magnant',
      'Majesty',
      'Malvinas 2032',
      'Mayday: Conflict Earth',
      'Mech Platoon',
      'Mega Lo Mania',
      'MegaGlest',
      'Men of War',
      'Meridian',
      'Metal Fatigue',
      'Metal Marines',
      'Micro Commandos',
      'Mission: Humanity',
      'Modem Wars',
      'Myth II: Soulblighter',
      'Myth III: The Wolf Age',
      'Myth: The Fallen Lords',
      'NATO Commander',
      'Napoleon',
      'Naval War: Arctic Circle',
      'Nemesis of the Roman Empire',
      'NetStorm: Islands At War',
      'Nether Earth',
      'Nexus: The Jupiter Incident',
      'Nightside',
      "No Man's Land",
      'North & South',
      'Northgard',
      'Ocean Battle',
      'Offworld Trading Company',
      'Original War',
      'Outlive',
      'Outpost 2: Divided Destiny',
      'Overwatch',
      'ParaWorld',
      'Pax Imperia Eminent Domain',
      'Perimeter',
      'Persian Wars',
      'Pikmin',
      'Planet X2',
      'Planetary Annihilation',
      'Populous',
      'Powermonger',
      'Praetorians',
      'Psi-5 Trading Company',
      'R.U.S.E',
      'Rage of Mages',
      'Re-Legion',
      'Real War',
      'Red Odyssey, The',
      'Reunion',
      'Rise and Fall: Civilizations at War',
      'Rise of Nations',
      'Rising Kingdoms',
      'Rising Lands',
      'Rival Realms',
      'Riverworld',
      'Rusted Warfare - RTS',
      'S.W.I.N.E.',
      'Sacrifice',
      'Sangokushi Battlefield',
      'Savage: The Battle for Newerth',
      'Sea Battle',
      'Sengoku',
      'Settlers',
      'Seven Kingdoms',
      'Shadow Sorcerer',
      'Siege',
      'Sins of a Solar Empire',
      'Skull Caps',
      'Smiley Commandos',
      'Soldiers: Heroes of World War II',
      'Space Colony',
      'SpellForce',
      'Spring 1944',
      'Spring project',
      'Stalin vs. Martians',
      'Star Command',
      'Star Trek',
      'Star Wars',
      'StarCraft',
      'Starship Troopers',
      'State of War',
      'Stellaris',
      'Steel Division',
      'Stellar Warfare',
      'Stonkers',
      'Stronghold',
      'Submarine Titans',
      'Sudden Strike',
      'SunAge',
      'Supremacy 1914',
      'Supremacy: Your Will Be Done',
      'Supreme Commander',
      'Supreme Ruler',
      'Svea Rike',
      'Swords & Soldiers',
      'Tanktics',
      'Taste of Power',
      'Thandor: The Invasion',
      'The Ancient Art of War',
      'The Golden Horde',
      'The Nations',
      'Theatre of War',
      'Theocracy',
      'They Are Billions',
      'Three Kingdoms',
      'Tone Rebellion, The',
      'Tooth and Tail',
      'Total Annihilation',
      'Total War',
      'Two Thrones',
      'Tzar: Burden of the Crown',
      'Universe at War',
      'Urban Assault',
      'Utopia',
      'ValeGuard',
      'Victoria: An Empire Under the Sun',
      'War Front: Turning Point',
      'Wargroove',
      'Warlords Battlecry',
      'War Incorporated',
      'War Party',
      'War Wind',
      'War of Legends',
      'War of Nerves!',
      'WarBreeds',
      'WarCraft',
      'Wargame',
      'WARSHIFT',
      'Dawn of War',
      'Warpath',
      'Warrior Kings',
      'Wars and Warriors',
      'Warzone 2100',
      'World War III',
      'World in Conflict',
      'WorldShift',
      'Z: Steel Soldiers',
      'Zero-K',
      'reconquest']